export default [
    {
        id: 1,
        title: "Osaka Castle",
        location: "Osaka, Japan",
        googleMapsUrl: "https://maps.app.goo.gl/iXy5xeW11qwkJ8TM9",
        startDate: "25 May, 2024",
        endDate: "25 May, 2024",
        description: "Osaka Castle (大坂城 or 大阪城, Ōsaka-jō) is a Japanese castle in Chūō-ku, Osaka, Japan. The castle and fortress are one of Japan's most famous landmarks and it played a major role in the unification of Japan during the sixteenth century of the Azuchi-Momoyama period.",
        rating: 4.5,
        comments: "Osaka Castle has an amazing mixture of beautiful architecture, scenic gardens, and history-rich exhibits. I would recommend visiting early morning to avoid the large crowds.",
        imageUrl: "osaka-castle.jpg"
    },
    {
        id: 2,
        title: "Dotonbori",
        location: "Osaka, Japan",
        googleMapsUrl: "https://maps.app.goo.gl/tEcCyRgNdKoFnTAp6",
        startDate: "26 May, 2024",
        endDate: "26 May, 2024",
        description: "Dōtonbori or Dōtombori (道頓堀) is a district in Osaka, Japan. Known as one of Osaka's principal tourist and nightlife areas, the area runs along the Dōtonbori canal from Dōtonboribashi Bridge to Nipponbashi Bridge in the Namba district of the city's Chūō ward. Historically a theater district, it is now a popular nightlife and entertainment area characterized by its eccentric atmosphere and large illuminated signboards.",
        rating: 4.0,
        comments: "Energetic spot with tons of great food and shopping options! Takoyaki and Okonomiyaki are a must-have!",
        imageUrl: "dotonbori-canal.jpg"
    },
    {
        id: 3,
        title: "Kifune Shrine",
        location: "Kibune, Japan",
        googleMapsUrl: "https://maps.app.goo.gl/upAJ9nGS5SyEvYT98",
        startDate: "27 May 2024",
        endDate: "27 May 2024",
        description: "Kifune Shrine (貴船神社, Kifune Jinja) is a Shinto shrine located at Sakyō-ku, Kyoto, Kyoto Prefecture Japan. From 1871 through 1946, the Kifune Shrine was officially designated one of the Modern system of ranked Shinto Shrines (官幣中社, Kanpei-chūsha), meaning that it stood in the second rank of government supported shrines.",
        rating: 4.2,
        comments: "Loved the quaint atmosphere and small-village vibes. Perfect amount of time for a half-day trip from Kyoto/Osaka to explore everything!",
        imageUrl: "kifune-shrine.png"
    },
    {
        id: 4,
        title: "Nishiki Market",
        location: "Kyoto, Japan",
        googleMapsUrl: "https://maps.app.goo.gl/QBcaX1mGK6Nyiket6",
        startDate: "27 May 2024",
        endDate: "27 May 2024",
        description: "Nishiki Market (錦市場) is a marketplace in downtown Kyoto, located on the east end of Nishikikōji Street, one block north and parallel to Shijō Street and west of Teramachi Street. Rich with history and tradition, the market is renowned as the place to obtain many of Kyoto's famous foods and goods.",
        rating: 4.0,
        comments: "A unique experience filled with tons of small stalls selling authentic Japanese street foods. The quality and freshness of the seafood is top-tier. Matcha warabi-mochi is a personal favorite of mine!",
        imageUrl: "nishiki-market.jpg"
    },
    {
        id: 5,
        title: "Philosopher's Path",
        location: "Kyoto, Japan",
        googleMapsUrl: "https://maps.app.goo.gl/bdiwUYZxRfqpoJ2Q7",
        startDate: "28 May 2024",
        endDate: "28 May 2024",
        description: "The Philosopher's Walk (哲学の道, Tetsugaku-no-michi, lit. Path of Philosophy) is a pedestrian path that follows a cherry-tree-lined canal in Kyoto, Japan between Ginkaku-ji and Nanzen-ji. First opened in 1890 and extended again in 1912, the path follows the course of a shallow irrigation channel bringing water from the Lake Biwa Canal.",
        rating: 3.6,
        comments: "A pleasant, picturesque walkway near several shrines and temples - perfect for pondering those philosophical thoughts 🥱",
        imageUrl: "philosophers-path.jpg"
    },
    {
        id: 6,
        title: "Shibuya Crossing",
        location: "Tokyo, Japan",
        googleMapsUrl: "https://maps.app.goo.gl/YiRjqtSENBHw3XYN8",
        startDate: "29 May 2024",
        endDate: "29 May 2024",
        description: "Shibuya Scramble Crossing (渋谷スクランブル交差点), commonly known as Shibuya Crossing, is a popular pedestrian scramble crossing in Shibuya, Tokyo, Japan. Shibuya Crossing is the world’s busiest pedestrian crossing, with as many as 3,000 people crossing at a time.",
        rating: 4,
        comments: "One of Japan's most iconic sights - surrounded by large crowds, animated signs, and neon lights. I'd recommend visiting at night 💯.",
        imageUrl: "shibuya-crossing.jpg"
    },
    {
        id: 7,
        title: "Akihabara Electric Town",
        location: "Tokyo, Japan",
        googleMapsUrl: "https://maps.app.goo.gl/JSbB6e2hrCwAFLL38",
        startDate: "29 May 2024",
        endDate: "29 May 2024",
        description: "Akihabara is considered by many to be the centre of Japanese otaku culture, and is a major shopping district for video games, anime, manga, electronics and computer-related goods. Icons from popular anime and manga are displayed prominently on the shops in the area, and numerous maid cafés and some arcades are found throughout the district.",
        rating: 4.2,
        comments: "A bustling neighbourhood filled with tiny stalls to huge venues specializing in manga, anime, and video games",
        imageUrl: "akihabara.jpg"
    },
    {
        id: 8,
        title: "Harajuku",
        location: "Tokyo, Japan",
        googleMapsUrl: "https://maps.app.goo.gl/KhnEGN721YG4uQbU6",
        startDate: "29 May 2024",
        endDate: "29 May 2024",
        description: "Harajuku is known internationally as a center of Japanese youth culture and fashion. Shopping and dining options include many small, youth-oriented, independent boutiques and cafés, but the neighborhood also attracts many larger international chain stores with high-end luxury merchandisers extensively represented along Omotesando.",
        rating: 3.5,
        comments: "Fun, flamboyant, and full of creative expression. Saw a lot of interesting cosplays and unique fashion from both tourists and locals!. Great place to visit for some souvenir shopping and pet cafés",
        imageUrl: "harajuku.jpg"
    },
    {
        id: 9,
        title: "Mt. Kawanori",
        location: "Tokyo, Japan",
        googleMapsUrl: "https://maps.app.goo.gl/BJ8ZhXKBKGoZf7HQ7",
        startDate: "30 May 2024",
        endDate: "30 May 2024",
        description: "Mount Kawanori (川苔山 Kawanori-yama) is a 1,363.3 meters high mountain located in Okutama area Tokyo. The approximate hiking time to the summit is 3 hours and 15 minutes from Hatonosu Station, 3 hours 45 minutes from Kori Station.",
        rating: 4.5,
        comments: "Exhilirating mountain hike with a great waterfall spot for pictures and breathtaking views at the summit. It's a little out of the way from Tokyo but definitely worth it for those adventurous souls!",
        imageUrl: "mt-kawamori.jpg"
    },
    {
        id: 10,
        title: "Omiya Bonsai Village",
        location: "Saitama, Japan",
        googleMapsUrl: "https://maps.app.goo.gl/rcvhZFuZ3eomLFNP9",
        startDate: "31 May 2024",
        endDate: "31 May 2024",
        description: " In 1925 Omiya Bonsai Village was established as an self-governed community of bonsai gardeners. At its height, in 1930, around 30 bonsai gardens were a part of the community. Even now Omiya Bonsai Village is known for its bonsai masterpieces attracting enthusiasts not only from Japan, but from around the world.",
        rating: 4.0,
        comments: "Strolled through Omiya Bonsai Village while on the way to Saitama. Pleasantly surprised by the beauty and craftmanship involved in bonsai!",
        imageUrl: "bonsai.jpg"
    },
    {
        id: 11,
        title: "Imperial Palace",
        location: "Tokyo, Japan",
        googleMapsUrl: "https://maps.app.goo.gl/RiasZLntcLcs2hbZA",
        startDate: "1 June 2024",
        endDate: "1 June 2024",
        description: "The Tokyo Imperial Palace is the main residence of the Emperor of Japan. It is a large park-like area located in the Chiyoda district of the Chiyoda ward of Tokyo and contains several buildings including the Fukiage Palace where the Emperor has his living quarters, the main palace where various ceremonies and receptions take place, some residences of the Imperial Family, an archive, museums and administrative offices.",
        rating: 4.0,
        comments: "Beautiful gardens and views. Will have to revisit someday since the palace was closed the day I went. 🥲 ",
        imageUrl: "imperial-palace.png"
    },
    {
        id: 12,
        title: "Tokyo Tower",
        location: "Tokyo, Japan",
        googleMapsUrl: "https://maps.app.goo.gl/bUxaH8LEWUobtHgg8",
        startDate: "1 June 2024",
        endDate: "1 June 2024",
        description: "The Tokyo Tower is a communications and observation tower in the Shiba-koen district of Minato, Tokyo, Japan, built in 1958. At 332.9 meters (1,092 ft), it was the tallest tower in Japan until the construction of Tokyo Skytree in 2012. The structure is an Eiffel Tower-inspired lattice tower that is painted white and international orange to comply with air safety regulations.",
        rating: 3.5,
        comments: "An iconic sight - looking down through the glass panes at the top floor was a whole different experience!",
        imageUrl: "tokyo-tower.jpg"
    },
    {
        id: 13,
        title: "Lake Ashi",
        location: "Hakone, Japan",
        googleMapsUrl: "https://maps.app.goo.gl/KmUyVwmgxyLgC7qV6",
        startDate: "3 June 2024",
        endDate: "3 June 2024",
        description: "Lake Ashi (芦ノ湖, Ashi-no-ko), also referred to as Hakone Lake or Ashinoko Lake, is a scenic lake in the Hakone area of Kanagawa Prefecture in Honshū, Japan. It is a crater lake that lies along the southwest wall of the caldera of Mount Hakone, a complex volcano that last erupted in 1170 CE at Ōwakudani. The lake is known for its views of Mount Fuji, its numerous hot springs, historical sites, and ryokan.",
        rating: 4.5,
        comments: "Took a day trip to Hakone and boarded the Lake Ashi sightseeing cruise. A bit pricey but worth it - especially if skies are clear!",
        imageUrl: "lake-ashi.png"
    },
    {
        id: 14,
        title: "Owakudani Kurotamagokan",
        location: "Hakone, Japan",
        googleMapsUrl: "https://maps.app.goo.gl/ChfytnjunUBh85F86",
        startDate: "3 June 2024",
        endDate: "3 June 2024",
        description: "A tourism facility located in the Owakudani valley. The facility’s famed “kurotamago” (“black eggs”) boiled eggs are cooked using the local geothermal heat and turn black from the influence of volcanic gasses; it is said one’s life is extended by seven years eating just one.",
        rating: 3.8,
        comments: "If you're planning on visiting Owakudani, definitely take the ropeway for some mesmorizing views on the way up and down!",
        imageUrl: "owakudani-jpg.jpg"
    },
    {
        id: 15,
        title: "Susukino",
        location: "Sapporo, Japan",
        googleMapsUrl: "https://maps.app.goo.gl/3sdrWB6jTBFXQehk9",
        startDate: "4 June 2024",
        endDate: "4 June 2024",
        description: "Susukino (すすきの) is a red-light district in Chūō-ku, Sapporo, Hokkaidō, Japan. It is one of the major red-light districts in Japan along with Kabukichō, Tokyo, and Nakasu, Fukuoka. Currently, the district is congested with many restaurants, bars, hotels, and adult-entertainment establishments.",
        rating: 4.3,
        comments: "Amazing place to visit at night ~ similar to Shibuya and Shinjuku in my opinion. Great food options and bars for end-of-day activities.",
        imageUrl: "susukino.png"
    },
    {
        id: 16,
        title: "Sapporo Beer Museum",
        location: "Sapporo, Japan",
        googleMapsUrl: "https://maps.app.goo.gl/d7kZ7jxyzEs2HNp37",
        startDate: "5 June 2024",
        endDate: "5 June 2024",
        description: "The Sapporo Beer Museum is a museum located in the Sapporo Garden Park in Sapporo, Japan. Registered as one of the Hokkaidō Heritage sites in 2004, the red-brick building was erected originally as a factory of the Sapporo Sugar Company in 1890, and later opened as a museum in 1987.",
        rating: 5,
        comments: "Incredible exhibits filled with history and culture with no admission fee! Combined with an authentic beer tasting on the 1st floor after exploring. 🍺",
        imageUrl: "beer-museum.jpg"
    },
]